### ISSUE TITLE
Theme Is Rendered Differently in SLIME REPL Mode on Linux and Mac

### ISSUE THREAD

**Issue by artforlife** [greduan/emacs-theme-gruvbox#100]
Greetings, 

I use Emacs on both Ubuntu and MacOS for programming work. After installing your theme, I noticed that it is rendered slightly differently on the two operating systems. In particular, the SLIME's `CL-USER>` prompt is of annoying red color when rendered on a Mac.

I am attaching a couple of screenshots. Could you tell me how I could troubleshoot this? Despite being a minor issue, it also renders the Rainbow-Blocks and Rainbow-Delimiters somewhat useless. That said, I am not sure if the latter is part of the same problem or is a separate issue on the Mac.

![Beautiful display on Ubuntu](https://user-images.githubusercontent.com/8064423/31640955-8323cf5c-b2af-11e7-9ddb-b9fa8b04ff6b.png)

![What seems like an incorrect display on MacOS](https://user-images.githubusercontent.com/8064423/31640992-c0504e14-b2af-11e7-854f-7a84f89ce2fd.png)

**Comment by jasonm23** [comment]
Hi, thanks for reporting the issue. Could you provide the Emacs version string for both.

**Comment by artforlife** [comment]
For Mac: 
`GNU Emacs 25.3.1
Copyright (C) 2017 Free Software Foundation, Inc.`

**Comment by jasonm23** [comment]
Is that reported by `M-x version`

**Comment by jasonm23** [comment]
It would help to know how you installed on the Mac too.  

Will need the Ubuntu version string (reported by `M-x version`)

**Comment by jasonm23** [comment]
Please confirm: the top screenshot is Ubuntu and bottom is Mac?

**Comment by jasonm23** [comment]
Also on Mac, running in Gui or Terminal?

**Comment by artforlife** [comment]
Answers:

- Top screenshot is Ubuntu 16.01. Bottom is MacOS Sierra 10.12
- MAc Version via `M-x version`:
<img width="571" alt="screen shot 2017-10-18 at 11 08 46 am" src="https://user-images.githubusercontent.com/8064423/31726411-e639aac6-b3f4-11e7-8e82-903b596ff8b6.png">

- Ubuntu Version (will edit tonight with details).

- Both versions running in GUI.

**Comment by jasonm23** [comment]
FYI any messages shown in the minibuffer will be appended to the `*Messages*` buffer, so you can avoid sending text as a screenshot.

(Please send the version as text so no one else has to re-type it, i.e. me :D )

**Comment by artforlife** [comment]
I included the Emacs version that runs on Ubuntu.  Thank you for the tip about the `Messages` buffer!

**Comment by jasonm23** [comment]
The method of installing Emacs on the Mac?
