### ISSUE TITLE
Highlighting in Emas-Lisp 

### ISSUE THREAD

**Issue by der-Daniel** [greduan/emacs-theme-gruvbox#101]
Hi,

when coding Elisp this looks like this.

![image](https://user-images.githubusercontent.com/7686866/32317508-4acbd0fc-bfb4-11e7-8d29-821f13932d01.png)

Why is `global-linum-mode` not highlighted like `setq` but like the comment.
Have I misconfigured the theme or is this a bug?

For Frodo.

**Comment by martijnat** [comment]
I do not have this problem on my machine.

![orgbabel](https://user-images.githubusercontent.com/22380358/32340090-e3f5fa56-bff9-11e7-9726-180c91863acb.png)


Could you tell me the following so we can narrow down the possible causes?

- Does this problem occur with other themes as well?

- Does this problem go away is you disable and then re-enable the gruvbox them?

- What version of emacs are you using? `M-x emacs-version`

- What version of org-mode are you using `M-x org-version`

- What minor modes do you have enable when using org-mode? `C-h m`

- What faces are used on the incorrectly highlighted face? Put your
  cursor/point on the wrongly highlighted word and press `C-u C-x =`
  to get a detailed buffer showing all relevant information


I suspect this bug is specific to org-mode. If this turns out to be
true, please file a bug report to the org-mode team.
http://orgmode.org/manual/Feedback.html

**Comment by der-Daniel** [comment]
Using the default theme, this problem also occurs:

![image](https://user-images.githubusercontent.com/7686866/32466359-fa4e451a-c346-11e7-9c12-476ab994b9a9.png)

Same for `darktooth`.
Reenabling the theme did not resolve the issue.

Using `C-c '` to edit the code block in a separate buffer yields the following highlighting.

![image](https://user-images.githubusercontent.com/7686866/32466425-3a677a54-c347-11e7-865a-0c786312ae60.png)

My Emacs version is 25.3.1.
My Org-mode version is 9.1.2.

List of Minor modes:
Async-Bytecomp-Package
Auto-Composition
Auto-Compression
Auto-Encryption
Auto-Revert
Blink-Cursor
Column-Number
Company
Delete-Selection
Diff-Auto-Refine
Drag-Stuff-Global
Electric-Indent
File-Name-Shadow
Flx-Ido
Flycheck
Font-Lock
Global-Company
Global-Eldoc
Global-Flycheck
Global-Font-Lock
Global-Git-Commit
Global-Hl-Line
Global-Linum
Global-Undo-Tree
Ido-Everywhere
Ido-Vertical
Line-Number
Magit-Auto-Revert
Mouse-Wheel
Override-Global
Projectile
Projectile-Rails-Global
Pyvenv
Recentf
Savehist
Shell-Dirtrack
Show-Smartparens
Show-Smartparens-Global
Smartparens
Smartparens-Global
Tex-Pdf
Tooltip
Transient-Mark
Undo-Tree
Which-Key
Winner
Yas
Yas-Global


Result of `C-u C-x =`:

                 position: 61943 of 67230 (92%), column: 19
                character: - (displayed as -) (codepoint 45, #o55, #x2d)
        preferred charset: ascii (ASCII (ISO646 IRV))
    code point in charset: 0x2D
                   script: latin
                   syntax: _ 	which means: symbol
                 category: .:Base, >:Not at bol, a:ASCII, l:Latin, r:Roman
                 to input: type "C-x 8 RET 2d" or "C-x 8 RET HYPHEN-MINUS"
              buffer code: #x2D
                file code: #x2D (encoded by coding system utf-8-unix)
                  display: by this font (glyph code)
        xft:-simp-Hack-normal-normal-normal-*-32-*-*-*-m-0-iso10646-1 (#x11)
    
    Character code properties: customize what to show
      name: HYPHEN-MINUS
      general-category: Pd (Punctuation, Dash)
      decomposition: (45) ('-')
    
    There are text properties here:
      face                 (org-block)
      font-lock-fontified  t
      font-lock-multiline  t
      fontified            t
      help-echo            nil
      src-block            t


I really appreciate your effort. It could be related to a different `mode` though I was not able to narrow it down yet. 
Maybe, if you compare it to your setup we can nail it down.

For Frodo

**Comment by martijnat** [comment]
At this point we at least know that the problem is not specific to gruvbox.

I am 99% certain this is an org-mode specific problem. The odd thing is that the grey line has the org-block face. This face should only be used for the BEGIN_SRC and END_SRC lines.

> Using C-c ' to edit the code block in a separate buffer yields the following highlighting.

When you edit using `C-c '`, the major mode actually changes. Unless you have some minor mode that changes colors and used in org-mode but not in emacs-lisp-mode, Its is a org-mode specific problem.

I suggest you try if this problem occurs even with a minimal config with no other packages loaded, and file a bug report with the org-mode team. The instruction for how to contact org-mode with bugs is available on their website: http://orgmode.org/manual/Feedback.html

**Comment by der-Daniel** [comment]
But using the code in a simple Elisp buffer looks like this
![image](https://user-images.githubusercontent.com/7686866/32518023-a3e33ae2-c408-11e7-9c87-b5ee0d287143.png)

It's still not as fancy as your even though org has no effect on this buffer.

**Comment by der-Daniel** [comment]
I also `rm -rf`'d my `elpa` directory and used `emacs -q` to install the theme in a complete vanilla setup.
Still the same in `org-mode` and `emacs-lisp-mode`.

**Comment by jasonm23** [comment]
Do you have a theme working as you'd expect for comparison

**Comment by martijnat** [comment]
> Using the default theme, this problem also occurs:

> I also rm -rf'd my elpa directory and used emacs -q to install the theme in a complete vanilla setup.

This is not something we can fix with this theme.

This issue requires a fix in org-mode (or potentially emacs). Send them a bug report and wait for a fix.

**Comment by jasonm23** [comment]
@martijnat thank you, that's what I thought.

**Comment by der-Daniel** [comment]
Thanks for your answers.
What is your Emacs and Org Version, so I can test your setup on my machine.

**Comment by martijnat** [comment]
On this current machine I am using debian and have installed emacs and
org mode from the stable repositories.

    Org-mode version 8.2.10 (release_8.2.10 @ /usr/share/emacs/25.1/lisp/org/)

    GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian

My config is also avaible online

   https://github.com/martijnat/.emacs.d

(just `M-x org-babel-load-file ~/.emacs.d/init.org` on the first run)

**Comment by der-Daniel** [comment]
![image](https://user-images.githubusercontent.com/7686866/32673236-a7f5a2da-c64e-11e7-996b-98ae288b2837.png)
After trying out several things, I still could not figure it out yet.
Even with the org-version of your machine something is just not right..

**Comment by jasonm23** [comment]
Sorry @der-Daniel I think you may have misunderstood us somewhere along the line 

Please let me reiterate, what you are seeing in org mode is as we expect, we don't see anything different.

If you are seeing the highlighting you want in another theme, please let me know what it is.  

To the best of our knowledge Org & Emacs do not highlight org code blocks the way they are highlighted in their major modes.

If you want to work with a specific set of languages and org you could try using mmm-mode or something similar which allows you to configure multi modes together.

**Comment by ninrod** [comment]
@der-Daniel, I do not have this problem on my machine. Try with latest org-mode. 

Also, it could be something within your configuration. Try to setup a minimal example. Like, starting from scratch, add gruvbox theme and try to reproduce.

**Comment by jasonm23** [comment]
@ninrod that's good news, can you post your org version number too please.

**Comment by der-Daniel** [comment]
Thank for keeping up the support in this issue. I still try to figure it out by changing my config step-by-step.
@jasonm23 I want to get the same highlighting as in the screenshots of the README.

**Comment by martijnat** [comment]
I hope you aren't changing your config line by line.

The best method for this is as follows:

- divide your config into two parts

- Comment the second part.

- Check if your problem still occurs.

- If the problem occurred, remove the second part

- If the problem did not occur, remove the first part and uncomment the
  second part.

- repeat until you have a minimal example.

**Comment by der-Daniel** [comment]
Yes thanks. 
I am still confused that even a minmal-minimal setup like only `gruvbox` and `emacs-lisp-mode` yields an incorrect highlighting. It looks like there is something deeper going on..

**Comment by der-Daniel** [comment]
Phew I finally found the issue!

The problem with the screenshots provided by the README of this repo is not representative because it is including the package `highlight-defined`.
This is nowhere mentioned. I found it by stepping through the config file looking for things hooking into `emacs-lisp-mode`.

**Comment by jasonm23** [comment]
![](https://raw.githubusercontent.com/greduan/emacs-theme-gruvbox/master/images/gruvbox-dark-medium-screenshot.png)

Facepalm! Oh I can't even remember if I made that or if it was @greduan

**Comment by greduan** [comment]
No org-mode magic from me haha. Good that it was found. 👍

**Comment by martijnat** [comment]
It was me.

I'll create a new set a screenshots with vanilla emacs later.

**Comment by martijnat** [comment]
A pull request is open https://github.com/greduan/emacs-theme-gruvbox/pull/102 for improved screenshots

**Comment by jasonm23** [comment]
:+1:

**Comment by der-Daniel** [comment]
Thank you all for the collaboration. 👍 
Keep up the good work.
