### ISSUE TITLE
gruvbox-light-medium in ansi-term

### ISSUE THREAD

**Issue by flooose** [greduan/emacs-theme-gruvbox#107]
### I'm submitting a:

- [ ] Feature request
- [x] Bug report

### Bug Report : 

The colors of the command prompt in ansi-term are are broken in gruvbox-light-medium. They seem to be using those of the previous theme.

### Please provide a relevant screenshot to illustrate the problem.

Here I'm using the spacemacs-dark color theme
![screenshot from 2018-01-23 11-37-12](https://user-images.githubusercontent.com/123168/35288109-e0ef693c-0031-11e8-8878-96285044233f.png)

and here I've switched to gruvbox-light-medium
![screenshot from 2018-01-23 11-43-47](https://user-images.githubusercontent.com/123168/35288464-bc2b0baa-0032-11e8-8b1d-6afe2237e400.png)

### Please tell us about your environment.

- OS version: Arch linux (current)
- Emacs version: GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2017-12-04
- spacemacs 0.200.11

**Comment by martijnat** [comment]
Thank you for the bug report.

I can replicate the issue by loading a second theme without unloading
the first theme. If I unload the first theme, either before or after
loading the gruvbox theme, I cannot replicate the issue.

Could you tell me the value of custom-enabled-themes in the second
screenshot? You can get the value using the command `M-x describe-variable custom-enabled-themes`

If this return something other than `(gruvbox-light-medium)` i.e.
`(gruvbox-light-medium spacemacs-dark)` it means you have multiple
themes enabled at once. You can then fix the issue either by using the
command `disable-theme` or by unselecting the theme using
`customize-themes`.

**Comment by flooose** [comment]
You're absolutely correct, `custom-enabled-themes` was set to `(gruvbox-light-medium spacemacs-dark)`. I never knew you could load multiple custom themes at the same time. `disable-theme` fixes the problem though, so I would say this issue is closed. Thanks for the info and the lovely color theme :)
