### ISSUE TITLE
python-mode changing the color of matched parentheses and brighter line numbers

### ISSUE THREAD

**Issue by haluk** [greduan/emacs-theme-gruvbox#108]
### I'm submitting a:

- [x ] Feature request

### Feature request (ignore if this is a bug report.)
I love the gruvbox-theme but the color of matched parentheses is not obvious as opposed to mismatched color. A blue variant color to matched parentheses can be better fit to a theme. Also, brighter line numbers would be great too.

### Please provide a relevant screenshot to illustrate the problem.
![screenshot from 2018-02-07 16-17-14](https://user-images.githubusercontent.com/183110/35944727-61b754e2-0c55-11e8-9a55-3965811e29b0.png)
![screenshot from 2018-02-07 16-17-29](https://user-images.githubusercontent.com/183110/35944728-61c51d70-0c55-11e8-877b-fd4593f7b551.png)

### Please tell us about your environment.
Emacs snapshot configured by prelude.

- OS version: Linux Mint 18.3 Cinnamon

- Emacs version:
GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2018-02-06

**Comment by martijnat** [comment]
I don't have time right now but I will look into it tomorrow.

Part of the problem is that the face contrasts badly with the line highlighting you have. It actually contrast decently with hl-line disable. I will have to try a few things to see what combinations work well.

Brighter line numbers is easy.

**Comment by martijnat** [comment]
This is what I came up with:

![hl-line-match](https://user-images.githubusercontent.com/22380358/35968131-434f9988-0cc3-11e8-8be4-91c69fc4b948.png)
![hl-line-mismatch](https://user-images.githubusercontent.com/22380358/35968132-436feed6-0cc3-11e8-80ee-c72e42890894.png)

Let me know if this works for you.

**Comment by haluk** [comment]
This looks good to me. Thanks.
