### ISSUE TITLE
[question] what font is this?

### ISSUE THREAD

**Issue by ninrod** [greduan/emacs-theme-gruvbox#110]
Hi, what font is this that you guys are using?

![ha](https://raw.githubusercontent.com/greduan/emacs-theme-gruvbox/master/images/gruvbox-dark-medium-screenshot.png)

**Comment by greduan** [comment]
If I'm not mistaken, looks like Luculent. http://eastfarthing.com/luculent/

**Comment by ninrod** [comment]
it seems like it, but the `k` of the luculent font isn't quite like it. Same for the `y`. it seems inspired in luculent though.

**Comment by ninrod** [comment]
it seems like it, but the `k` of the luculent font isn't quite like it. Same for the `y`. it seems inspired in luculent though. maybe @martijnat can provide a hint.

**Comment by martijnat** [comment]
The font is [Fantasque Sans Mono](https://github.com/belluzj/fantasque-sans)

**Comment by ninrod** [comment]
@martijnat thank you!
