### ISSUE TITLE
which-func face too dark

### ISSUE THREAD

**Issue by a-dma** [greduan/emacs-theme-gruvbox#112]
### I'm submitting a:
- [x] Feature request
- [ ] Bug report

### Feature request (ignore if this is a bug report.)
The `which-func` face is set do `Blue1` which appears to be completely off and quite hard to read.
It would be nicer to use one of the two blues in the palette (`#005f87` being the better one IMHO).

### Please provide a relevant screenshot to illustrate the problem.
![screenshot](https://user-images.githubusercontent.com/711165/37352619-f6a7df48-26dd-11e8-832f-4cddb5473602.png)

### Please tell us about your environment.

- OS version: Ubuntu 17.10

- Emacs version: GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian

**Comment by martijnat** [comment]
I made a pull request for the changes here: https://github.com/greduan/emacs-theme-gruvbox/pull/113

![1520958851-window](https://user-images.githubusercontent.com/22380358/37356860-42b732b8-26e7-11e8-8fb9-dd3f325a8ccd.png)
![1520958866-window](https://user-images.githubusercontent.com/22380358/37356861-42e007d8-26e7-11e8-93ae-c01971f1629f.png)


#005f87 is barely readable so I chose to use the bright-blue color.

Once a second maintainer has had a quick look at it, it will be merged.

**Comment by a-dma** [comment]
Great thanks!

Also, kind of hijacking my own issue here, but I would like to respectfully suggest you guys take a look at the [base16](https://github.com/belak/base16-emacs/blob/master/build/base16-gruvbox-dark-medium-theme.el) version of gruvbox.
I know this is mostly subjective, but I think they do a couple of nice things, specifically the modeline orange highlights and the slightly darker default face (at least in the dark-medium variant). Unfortunately their version requires truecolor support and doesn't work when run with `-nw` unlike yours.
Just an idea :)

**Comment by greduan** [comment]
@a-dma so the issues don't get mixed up, feel free to open a new issue for that 🙂

**Comment by a-dma** [comment]
@greduan indeed, sorry. Since it was just a passing remark mostly based on personal taste, I didn't want to create a separate issue and make more noise :)

I'll sit on it a while longer and open a new issue in case.
Thanks.
