### ISSUE TITLE
Ido support

### ISSUE THREAD

**Issue by j3ky** [greduan/emacs-theme-gruvbox#115]
### I'm submitting a:

Hey Ive implemented gruvbox to` Ido-mode` :
https://i.imgur.com/A901DmU.png

```(custom-set-faces
 '(ido-subdir ((t (:foreground "#ffaf00")))) ;; Face used by ido for highlighting subdirs in the alternatives.
 '(ido-first-match ((t (:foreground "#fb4933")))) ;; Face used by ido for highlighting first match.
 '(ido-only-match ((t (:foreground "#ffcc33")))) ;; Face used by ido for highlighting only match.
 '(ido-indicator ((t (:foreground "#ffffff")))) ;; Face used by ido for highlighting its indicators (don't actually use this)
 '(ido-incomplete-regexp ((t (:foreground "#ffffff")))) ;; Ido face for indicating incomplete regexps. (don't use this either)
 )
```
- [x] Feature request
- [ ] Bug report

### Please tell us about your environment.

- OS version: Debian GNU Linux

- Emacs version: 26.1

    (use `M-x version` then copy the version string from `**Messages**`)

- If your report is about a specific Emacs major or minor mode, please
  let us know how it was installed (MELPA, ELPA, by hand, etc.) and
  the major/minor-mode version number.

**Comment by jasonm23** [comment]
Please submit as a pull request

Thank you

**Comment by jasonm23** [comment]
ido support updated in 1.25.0
