### ISSUE TITLE
Default text color of gruvbox-dark-* is too bright for my eyes.

### ISSUE THREAD

**Issue by crocket** [greduan/emacs-theme-gruvbox#120]
I'm currently using gruvbox-dark-medium. The contrast between background and foreground is higher than the original. This is painful to my vision.

For example, the text color should be `ebdbb2`, but it is actually `fdf4c1` on emacs.

This is bad for night time reading.

**Comment by jasonm23** [comment]
Apologies for the late response.

Would you be able to send us a pull request.

**Comment by crocket** [comment]
I looked for `fdf4c1` in `gruvbox-dark-medium-theme.el`. It was the first column of `gruvbox-light0`.
The first column of `gruvbox-light1` is `ebdbb2`.

I don't understand the data structure.

**Comment by jasonm23** [comment]
Ok. I'll take a look.

**Comment by bataak** [comment]
Actually, I use gruvbox in my vim editor and I thought emacs-theme-gruvbox was exactly same with original one. But it didn't.

**Comment by crocket** [comment]
I checked again. It isn't fixed, yet.

**Comment by jasonm23** [comment]
Please note Gruvbox is 100% community maintained and driven.

Administrators and owner will only review and approve / reject pull requests for bug fixes and/or extensions.

Thank you.

**Comment by crocket** [comment]
Can you at least reopen this issue?

**Comment by jasonm23** [comment]
Done, sorry, I thought you would be able to.
