### ISSUE TITLE
Source blocks in org-mode 

### ISSUE THREAD

**Issue by chama-chomo** [greduan/emacs-theme-gruvbox#123]
### I'm submitting a:

- [x] Feature request
- [ ] Bug report

### Feature request (ignore if this is a bug report.)
The only thing I'm missing in this great theme is that source blocks in org-mode are not visually 
separated from the rest of the text. Can this be improved, please?

### Please provide a relevant screenshot to illustrate the problem.
![image](https://user-images.githubusercontent.com/34240896/51278927-38ebfc80-19dc-11e9-8207-56d776011ff1.png)

### Please tell us about your environment.

- OS version:

- Emacs version:
26.1
    (use `M-x version` then copy the version string from `**Messages**`)

- If your report is about a specific Emacs major or minor mode, please
  let us know how it was installed (MELPA, ELPA, by hand, etc.) and
  the major/minor-mode version number.

**Comment by jasonm23** [comment]
Apologies for the late response.

Could you provide example(s) of how you think this could be improved.

**Comment by chama-chomo** [comment]
Hello, if you don't mind I'm gonna provide only examples taken from another hi-quality themes (monokai, spacemacs)

![image](https://user-images.githubusercontent.com/34240896/53400747-d4df2f80-39ae-11e9-8e3e-8f36f6d9a611.png)

![image](https://user-images.githubusercontent.com/34240896/53400791-ea545980-39ae-11e9-9a9d-bc743e03a067.png)

I'd probably go for a different background color in blocks

**Comment by chama-chomo** [comment]
Guys, may I hope for an update in a near future? Is it feasible for you to make this improvement? Thanks a lot for a good work.

**Comment by jasonm23** [comment]
Gruvbox is essentially community driven.  We don't ask for payments or anything like that.

We provide the framework and our users contribute features they want.

If you want to contribute a pull request to add code blocks for Org, we welcome it.

However we all have full time jobs and very scarce free time with families and what not.

Hope you understand.

**Comment by chama-chomo** [comment]
Jason, I'm sorry for this misunderstanding, my query was all but pushing you. It was rather to find out whether there is a possibility for you take a look on your side, so I'm not spending hours by figuring out how things work. I guess this change will be relatively easy for someone who is already onboard. I apologize for being unpolite.

**Comment by jasonm23** [comment]
Sorry if I gave you the wrong impression, I was just trying to make sure that you understood how Gruvbox is developed.

If you need help with implementation we are all happy to look at things with you.

What we likely won't be able to spend time doing is digging up the implementation from other themes.

As you have another theme which is doing this theming nicely, I'd encourage you to have a look at the org- prefixed customisation in that theme and it should be quite simple to see what you'd need to add to Gruvbox.

If that seems non-obvious, I think it makes sense to ask specific questions where obviousness drops off for you.

**Comment by 97-109-107** [comment]
@chama-chomo this should point you in the right direction on how to add this in your own setup https://emacs.stackexchange.com/a/14868

**Comment by fbkarsdorp** [comment]
Indeed, as @97-109-107 points to, you can easily customize the colors using something like:

```elisp
(custom-set-faces
  '(org-block ((t (:background "#32302f"))))
  '(org-block-begin-line ((t (:inherit org-meta-line :background "#3c3836")))))
```

**Comment by chama-chomo** [comment]
I have added below to gruvbox.el and org blocks look pretty good now.
```
(org-block                                 (:background gruvbox-dark0_soft))
(org-block-begin-line                      (:background gruvbox-dark1))
(org-block-end-line                        (:background gruvbox-dark1))
```
![image](https://user-images.githubusercontent.com/34240896/56678349-c5d0e100-66c2-11e9-931e-4a8f80636df7.png)
I haven't checked other variants though, for accepting a new pull request would you need all variants edited? Thanks for your help

**Comment by jasonm23** [comment]
Hi @chama-chomo it'll be fine to add on more support for other variants as you go.

If you add in the essentials that'll be great
