### ISSUE TITLE
Typo in org-drawer color definition

### ISSUE THREAD

**Issue by JulHee** [greduan/emacs-theme-gruvbox#126]
### I'm submitting a:

- [ ] Feature request
- [X] Bug report

### Bug Report : Describe the problem in your own words

First of all, thank you for this wonderful theme.

I found a bug, if you want to generate a css file  based on the current buffer (`M-x org-html-htmlize-generate-css`), emacs displays the error "Invalid face: font-lock-function-face". I think, the problem is due to a typo in 
[gruvbox.el](https://github.com/greduan/emacs-theme-gruvbox/blob/master/gruvbox.el#L326) which should have been:

` (org-drawer (:inherit 'font-lock-function-name-face))`

After fixing the typo `org-html-htmlize-generate-css` works as expected. I created an pull request with my changes (#127 ).

### Please provide a relevant screenshot to illustrate the problem.

![gruvbox_error](https://user-images.githubusercontent.com/9954356/51760427-b0034e00-20ca-11e9-8d3b-da1d75af3aa1.png)

### Please tell us about your environment.

- OS version: `Ubuntu 18.04.1 LTS` 

- Emacs version: `GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-2`

    (use `M-x version` then copy the version string from `**Messages**`)

- If your report is about a specific Emacs major or minor mode, please
  let us know how it was installed (MELPA, ELPA, by hand, etc.) and
  the major/minor-mode version number.

Update: Added link to pull request

**Comment by greduan** [comment]
Fixed by linked PR.
