### ISSUE TITLE
Function for accessing gruvbox color hex values by name

### ISSUE THREAD

**Issue by cvanderwall14** [greduan/emacs-theme-gruvbox#131]
### I'm submitting a:

- [x] Feature request
- [ ] Bug report

### Feature request
Function for accessing the hex values of gruvbox colors by their names.

Something like:
```
(gruvbox-color 'gruvbox-dark0) ; => "282828"
(gruvbox-color 'gruvbox-dark0 '256) ; => "262626"
```

Here's an example of how doom-themes does it:
```
;;;###autoload
(defun doom-color (name &optional type)
  "Retrieve a specific color named NAME (a symbol) from the current theme."
  (let ((colors (if (listp name)
                    name
                  (cdr-safe (assq name doom-themes--colors)))))
    (and colors
         (cond ((listp colors)
                (let ((i (or (plist-get '(256 1 16 2 8 3) type) 0)))
                  (if (> i (1- (length colors)))
                      (car (last colors))
                    (nth i colors))))
               (t colors)))))
```

**Comment by jasonm23** [comment]
Given that features would usually be discussed as user stories, could you share the use case / user story that you have for this?

**Comment by cvanderwall14** [comment]
As a user, I would like to access colors from the gruvbox theme in my
config.

For example:
As a user using `evil-mode`, I would like to set my cursor color to
`gruvbox-faded_yellow` when in `emacs` state.

```
(setq evil-emacs-state-cursor '(box (gruvbox-color 'gruvbox-faded_yellow)))
```

**Comment by cvanderwall14** [comment]
As a user, I would like to access colors from the gruvbox theme in my config.

For example:
As an `evil-mode` user, I would like to set my cursor color to `gruvbox-faded_yellow` when in `emacs` state. 

```
(setq evil-emacs-state-cursor '(box (gruvbox-color 'gruvbox-faded_yellow)))
```

**Comment by jasonm23** [comment]
Thanks for the info.  

So in effect you want to build gruvbox specific extensions into your config.
