### ISSUE TITLE
Neotree faces break gruvbox when neotree is not in use

### ISSUE THREAD

**Issue by TimoFreiberg** [greduan/emacs-theme-gruvbox#133]
### I'm submitting a:

- [X ] Bug report

### Bug Report : Describe the problem in your own words
Since bacc441f67a18975eea4cd18af64c069b6d3918f, I can't use the gruvbox theme.
I use treemacs instead of neotree so I get a `error: (void-variable neo-banner-face)`
I guess this could be an autothemer bug, maybe it should check if the variable is void before using it...

Backtrace here: https://gist.github.com/TimoFreiberg/9276eb0ee2eb3f0d3bd1b577e75e3950

### Please tell us about your environment.

- OS version:
Linux (Arch)

- Emacs version:
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.7) of 2019-03-17
Installed by spacemacs

**Comment by atharvashukla** [comment]
Facing the  same issue, with `(void-variable neo-banner-face)`.

**Comment by StarGazerM** [comment]
same issue
