### ISSUE TITLE
Colors are slightly different in GUI and terminal

### ISSUE THREAD

**Issue by hmenke** [greduan/emacs-theme-gruvbox#139]
### I'm submitting a:

- [ ] Feature request
- [x] Bug report

### Bug Report:

The colors are different in the GUI and terminal. For example when color-picking the background in the attached screenshot, I get `#282828` for the GUI (left side) and `#262626` for the terminal (right side).

### Please provide a relevant screenshot to illustrate the problem.

Left is GUI, right is terminal.  Click to enlarge.

![screenshot](https://user-images.githubusercontent.com/1903556/57498503-379a6300-7330-11e9-8177-4eae0a900bdc.png)

### Please tell us about your environment.

- OS version: Ubuntu 18.04.2 LTS

- Emacs version: GNU Emacs 25.2.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2017-09-23, modified by Debian

- Terminal: Reproducible in GNOME Terminal, MATE Terminal, XTerm.

    ```console
    $ echo $TERM
    xterm-256color
    ```

**Comment by greduan** [comment]
This is not something that can be avoided if your terminal doesn't support true color (i.e. 24-bit color).

The terminal's 256 colors simply does not contain the 16 million possible colors the GUI can make 🙂 

I checked this [256 colors list](https://jonasjacek.github.io/colors/) and indeed `#282828` is not a color there, but `#262626` is.

Does that answer your question?

**Comment by hmenke** [comment]
That's interesting.  For some reason Vim and NeoVim are able to properly display `#282828` in the terminal.  However, for this to work one has to add `set termguicolors` to the `.vimrc`.

Left is terminal Emacs, right is terminal NeoVim.
![](https://user-images.githubusercontent.com/1903556/58013033-4c6fb700-7ae5-11e9-9371-507fcafc99ed.png)

**Comment by jasonm23** [comment]
https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html assuming you've checked this.

**Comment by jasonm23** [comment]
BTW please note this is not a bug report.  This is related to Emacs support for 24 bit terminals.
