### ISSUE TITLE
Support erc 

### ISSUE THREAD

**Issue by lugubris** [greduan/emacs-theme-gruvbox#142]
### I'm submitting a:

- [x] Feature request

### Feature request

erc is not supported currently, default colors don't look nice.

### Please provide a relevant screenshot to illustrate the problem.

![2019-09-15-141326_1920x1080_scrot](https://user-images.githubusercontent.com/54440948/64922830-1e646000-d7c3-11e9-9c78-9312cb80e9a7.png)

### Please tell us about your environment.

- OS version: Void Linux x86_64

- Emacs version: GNU Emacs 26.3 (build 1, x86_64-unknown-linux-gnu, X toolkit) of 2019-08-29

- If your report is about a specific Emacs major or minor mode, please
  let us know how it was installed (MELPA, ELPA, by hand, etc.) and
  the major/minor-mode version number.

erc is included in emacs

**Comment by holtzermann17** [comment]
I think this can close as of 09d9a94e1c9036653fa1291c72a4daf85415af50
