### ISSUE TITLE
Compile theme to one single file without dependencies

### ISSUE THREAD

**Issue by Crandel** [greduan/emacs-theme-gruvbox#144]
### I'm submitting a:

- [x] Feature request

### Feature request (ignore if this is a bug report.)
Is it possible to compile set of files to one theme file without extra dependencies(like autothemer or cl-lib)?
I used to use a **dark-mint-theme** and put it before any packaging installation or loading happens to have dark theme from scratch.

### Please tell us about your environment.

- OS version:
Arch linux
- Emacs version:
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29

**Comment by jasonm23** [comment]
No fix
