### ISSUE TITLE
Manual install instructions are not complete

### ISSUE THREAD

**Issue by rayx** [greduan/emacs-theme-gruvbox#145]
The [manual install procedure](https://github.com/greduan/emacs-theme-gruvbox#no-packageel) contains only the instructions about setting up loading theme files. However, all theme files depends on gruvbox.el. If that file is not located in `load-path`, emacs would fail to load the theme.

The following code change fixes the issue for me. I think the change also works with melpa (though I didn't verify it).

    -(require 'gruvbox)
    +(require 'gruvbox
    +         (locate-file "gruvbox.el" custom-theme-load-path))

BTW, it would be good to mention that gruvbox depends on autothemer and user should install that package first.

(FWIW, I switch back to solarized after trying the theme because I find I like its low brightness contrast very much :)

**Comment by jasonm23** [comment]
Updates
