### ISSUE TITLE
Smart-mode-line support is incomplete

### ISSUE THREAD

**Issue by sdevlin** [greduan/emacs-theme-gruvbox#148]
### I'm submitting a:

- [ ] Feature request
- [x] Bug report

### Bug Report : Describe the problem in your own words

Gruvbox defines several faces to support smart-mode-line; however, smart-mode-line defines multiple other faces that gruvbox does not. For example, smart-mode-line defines the following:

`(defface sml/modified         '((t :inherit sml/not-modified :foreground "Red" :weight bold))
  "" :group 'smart-mode-line-faces)`

The modified marker uses the default red rather than gruvbox's palette. See the screenshot below.

Gruvbox should update its support for smart-mode-line faces.

### Please provide a relevant screenshot to illustrate the problem.

<img width="134" alt="Screen Shot 2019-10-16 at 10 33 36 AM" src="https://user-images.githubusercontent.com/174996/66943647-75e32f00-f000-11e9-896a-edebc991a05c.png">

**Comment by jasonm23** [comment]
We would welcome a pull request to extend the cover of smart-modeline, or any other Emacs modes.
