### ISSUE TITLE
ediff session is unreadable

### ISSUE THREAD

**Issue by rolandg** [greduan/emacs-theme-gruvbox#149]
### I'm submitting a:
- [x] Bug report

### Bug Report : Describe the problem in your own words
ediff session is unreadable

### Please provide a relevant screenshot to illustrate the problem.
![image](https://user-images.githubusercontent.com/1443267/73304945-80c17880-4219-11ea-928e-4b068ee28bc6.png)

### Please tell us about your environment.

- OS version:
linux
- Emacs version:
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29
- If your report is about a specific Emacs major or minor mode, please
  let us know how it was installed (MELPA, ELPA, by hand, etc.) and
  the major/minor-mode version number.

I'm using spacemacs develop branch.
gruvbox-theme-20190720.337

**Comment by jasonm23** [comment]
We recommend submission of a pull request to add improvement to mode support.

**Comment by rolandg** [comment]
Any hints where to start digging?

**Comment by ianpan870102** [comment]
@rolandg I just checked, there's none to be dug because the ediff config is lacking. If one wants to submit a PR then s/he'd had to fully add new tweaks for ediff (e.g.  faces like `ediff-even-diff-A`, `ediff-even-diff-B`, `ediff-odd-diff-A` etc).

**Comment by jasonm23** [comment]
Should have commented on this one sooner, sorry.

As Gruvbox is community driven, missing mode support is not considered to
be a bug.

PRs are appreciated and they are the way the theme has progressed and
developed over several years.

Even partially adding supporting a mode is a useful contribution.

So to underline, this issue will remain open.

However as there is no core support & maintenance developer team.  The
maintenaners will only assess PR quality and reject or approve (sometimes
amend & approve) and merge, code which addresses this or any other issue.

**Comment by ssnnoo** [comment]
maybe like this [this](https://github.com/greduan/emacs-theme-gruvbox/pull/157#issue-409718819)?

**Comment by jasonm23** [comment]
@ssnnoo Good start.  I'll approve & merge.

Thank you

**Comment by jasonm23** [comment]
Please note this will be in the unstable release on MELPA
