### ISSUE TITLE
Inconsistency between helm-selection-line and ivy-current-match

### ISSUE THREAD

**Issue by AndreaOrru** [greduan/emacs-theme-gruvbox#161]
### I'm submitting a:

- [x] Feature request
- [ ] Bug report

### Feature request (ignore if this is a bug report.)
In all Gruvbox themes, `helm-selection-line` makes use of a `gruvbox-dark2` background to highlight the currently selected element. The equivalent functionality in Ivy (`ivy-current-match`) uses underlining. I personally believe the choice made for Helm is better, and it should be adopted for both completion frameworks (if nothing else, for consistency).

### Please provide a relevant screenshot to illustrate the problem.
![image](https://user-images.githubusercontent.com/3673952/81469708-7b64c880-9221-11ea-8b6d-6bde43a259b9.png)

### Please tell us about your environment.

- OS version:
Arch Linux (Linux 5.6.11)

- Emacs version:
GNU Emacs 27.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.17.3) of 2020-05-08

**Comment by AndreaOrru** [comment]
Separately, and related to this: any good reason why we're forcing both Helm's and Ivy's foreground to be white? That hides syntax highlighting when using `helm-swoop` and `swiper`.

**Comment by jasonm23** [comment]
Thanks for the feature suggestion.  Gruvbox has been community driven for a
while now so certain inconsistent settings and choices like this happen.

>
We invite all users to fix things via GitHub pull requests and make Gruvbox
better collectively.

We cannot guarantee prompt action on feature requests via other means.

Pull requests should feature before and after images so anyone interested
may comment at a glance.

Thanks again.
