### ISSUE TITLE
Typo on aw-background-face foreground attribute

### ISSUE THREAD

**Issue by jpalaciosdev** [greduan/emacs-theme-gruvbox#162]
### I'm submitting a:

- [ ] Feature request
- [x] Bug report

### Bug Report : Describe the problem in your own words
aw-background-face has a typo on :foreground attribute.

### Please tell us about your environment.

- OS version: Archlinux

- Emacs version: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20) of 2020-05-19

**Comment by jasonm23** [comment]
Thanks for reporting and fixing
