### ISSUE TITLE
tabbar-use-images nil color is the same as the background

### ISSUE THREAD

**Issue by xorb0ss** [greduan/emacs-theme-gruvbox#167]
### I'm submitting a:

- [ ] Feature request
- [x] Bug report

### Bug Report

When setting `tabbar-use-images` to nil, gruvbox makes the ASCII buttons are invisible (they’re there and clickable, just the same color as the background I think?)

In the screenshot below this is apparent:

### Please provide a relevant screenshot to illustrate the problem.

![39148CB6-376D-4442-9A57-3C012988E52C](https://user-images.githubusercontent.com/9213716/89790220-84fc1600-db19-11ea-9c44-ac54a54cde9a.jpeg)

### Please tell us about your environment.

- OS version: Arch Linux

- Emacs version: 26.3

tabbar was installed through MELPA and is version 2.2 and I’m on Gruvbox dark medium

**Comment by jasonm23** [comment]
Please note Gruvbox development is 100% community driven.

Features which you'd like to see delivered, should take the form of a pull
request.
