### ISSUE TITLE
gruvbox-dark-soft background and company-tooltip are identical

### ISSUE THREAD

**Issue by 95440b97d** [greduan/emacs-theme-gruvbox#176]
### I'm submitting a:

- [ ] Feature request
- [x] Bug report

### Bug Report : Describe the problem in your own words
gruvbox-dark-soft background and company-tooltip face are identical.

### Please provide a relevant screenshot to illustrate the problem.

![gruvbox-dark-soft](https://user-images.githubusercontent.com/22228993/106376928-3d03d080-6391-11eb-8e67-4273524aa7fb.png)

### Please tell us about your environment.

- Emacs version:

Emacs version: 27.1
Gruvbox installed from MELP (gruvbox-theme-20210105.1136)

**Comment by 95440b97d** [comment]
A fix would be to not use the `gruvbox-dark0_soft` color for the faces `company-scrollbar-fg` and `company-tooltip`.

I suggest to use the following colors for the following faces:
```lisp
;; gruvbox.el
(company-scrollbar-bg (:background gruvbox-dark2))  
(company-scrollbar-fg (:background gruvbox-dark1))  
(company-tooltip (:background gruvbox-dark1))
```

Which gives the following result:
![gruvbox-light-soft-fix](https://user-images.githubusercontent.com/22228993/106398584-87c22e80-640b-11eb-9235-e08d3481811e.png)

The new colors work for all gruvbox-dark and light faces.

**Comment by ssnnoo** [comment]
how does your suggestion look with the light theme?

**Comment by 95440b97d** [comment]
The proposed change does not change the light theme. The problem described in this bug report only exist in the gruvbox-dark-light color palette.

For reference here's a screenshot of gruvbox-light-soft:
![gruvbox-light-soft](https://user-images.githubusercontent.com/22228993/107421458-e70df600-6b11-11eb-81be-453eafeb20a9.png)

**Comment by ssnnoo** [comment]
yes, unfortunately the separate files that define soft etc. only assigned colours, which colour identifier (gruvbox-dark2, dark1 etc.) is used for a specific face is defined for all themes in gruvbox.el. Hence, with the current code design one would need to change the colour identifier for company tooltip for all theme flavours.

**Comment by 95440b97d** [comment]
Perhaps so but the suggested change works for dark-soft/medium/hard as well as for all light variants.

**Comment by BooAA** [comment]
I have the same problem here, the background of company-tooltip can not be distinguished from the background of Emacs.  @95440b97d's fix looks good to me.

**Comment by ssnnoo** [comment]
I prepared [this pull request](https://github.com/greduan/emacs-theme-gruvbox/pull/178#issue-661602185) with the suggested fix. Of course anyone of you could also have done it :-).

**Comment by ssnnoo** [comment]
Close this one? :-)
