### ISSUE TITLE
Support Avy mode

### ISSUE THREAD

**Issue by azzamsa** [greduan/emacs-theme-gruvbox#184]
### I'm submitting a:

- [ X] Feature request

### Feature request (ignore if this is a bug report.)

[Avy](https://github.com/abo-abo/avy) is not supported currently, default colors don't look nice.

### Please provide a relevant screenshot to illustrate the problem.

- avy-goto-line

![image](https://user-images.githubusercontent.com/17734314/150281011-a9865b10-1951-4d42-9a14-07dff264fe4e.png)

- avy-goto-char-timer

![image](https://user-images.githubusercontent.com/17734314/150281065-fcbe9ca2-6bc0-45fa-955f-a4ca8ed2f62f.png)

### Please tell us about your environment.

- OS version:

OS: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-10-amd64

- Emacs version:

Emacs version: GNU Emacs 29.0.50 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2021-12-28

**Comment by P233** [comment]
`gruvbox-light1` for the foreground color of `avy-lead-face` in light themes is difficult to read. Can we have a more light foreground? 

<img width="546" alt="Screen Shot 2022-07-23 at 17 29 21" src="https://user-images.githubusercontent.com/1818679/180599594-c27d94fc-70c7-4284-9133-b2e7b2968e7b.png">
<img width="536" alt="Screen Shot 2022-07-23 at 17 29 36" src="https://user-images.githubusercontent.com/1818679/180599595-a26c6e91-1227-4244-9480-a5fd3ebe5b08.png">

**Comment by jasonm23** [comment]
Please review the theme palette and suggest alternatives.

Better still, apply the change, test it, screenshot it and post the code as a pull request.

If you need help with that, let me know.

**Comment by P233** [comment]
Thanks @jasonm23 for the quick reply, and @ethanmoss1 for adding Avy support.

The `gruvbox-light*` and `gurvbox-dark*` are assigned opposite colors in dark and light themes. I am not sure how to conditionally use them in [gruvbox.el](https://github.com/greduan/emacs-theme-gruvbox/blob/master/gruvbox.el). Therefore, I guess maybe we can directly use the `gruvbox-white` ?

Here are the screenshorts:
<img width="664" alt="Screen Shot 2022-07-23 at 21 25 30" src="https://user-images.githubusercontent.com/1818679/180609012-5671a2b7-be73-49d0-b133-506067f182bc.png">
<img width="669" alt="Screen Shot 2022-07-23 at 21 25 57" src="https://user-images.githubusercontent.com/1818679/180609016-ea69ea2c-9967-478e-a285-7ae6f58a90e1.png">

If it is acceptable, would love to submit a PR.

Not sure if there is any better solution for this.

**Comment by jasonm23** [comment]
Ok these look good to me for the momentary display of Avy jump tokens.

Please go ahead and submit the change as a PR

**Comment by jasonm23** [comment]
One thought perhaps the background colors of the tokens should be from the core palette of foreground colors.

Have a play and decide for yourself if you like the results

**Comment by ethanmoss1** [comment]
Any thoughts on using the gruvbox_dark0 and having the text be the same as the background, allowing the colour to 'pop'? tried it and it looks good. I can always do the PR once we're set on colours.

**Comment by jasonm23** [comment]
Looks more like Gruvbox to me.  I think that's perfect,

**Comment by P233** [comment]
Much better, thank you all 🎉🎉
