### ISSUE TITLE
`Warning: setting attribute ‘:background’ of face …: nil value is invalid, use ‘unspecified’ instead`

### ISSUE THREAD

**Issue by mekeor** [greduan/emacs-theme-gruvbox#195]
### Bug Report

When using this theme, and e.g. invoking `diff-hl-mode`, you'll get the following warnings in your `*Messages*` buffer:

```
Warning: setting attribute ‘:background’ of face ‘diff-refine-added’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:background’ of face ‘diff-refine-removed’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:background’ of face ‘diff-added’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:background’ of face ‘diff-removed’: nil value is invalid, use ‘unspecified’ instead.
```

### Environment

- OS version: Guix System 3ae6f30767f962da74d18d824b521462e149b89a
- Emacs version: GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw scroll bars)

**Comment by jasonm23** [comment]
Since "unspecified" was introduced in 29.x, the fix will need to be implemented as backwards compatible.

**Comment by jasonm23** [comment]
Potentially we can add a feature to Autothemer to fix this. I'll open an issue there.

**Comment by jasonm23** [comment]
Ok, I've done some research and basically it's for values you don't want to specify, and they should implicitly inherit.  I may not have explained that perfectly, but please refer to this https://github.com/syl20bnr/spacemacs/pull/15877 spacemacs issue for more context.

It is currently only generating warnings for `:background` so we will only make that change.

Other attributes will be left as nil, for the moment.
