### ISSUE TITLE
Hide `gruvbox-deftheme` and `gruvbox-screenshot` from end-user

### ISSUE THREAD

**Issue by mekeor** [greduan/emacs-theme-gruvbox#197]
### Feature request

When this theme is loaded, it exposes `gruvbox-deftheme` and `gruvbox-screenshot` commands. These are not meant to be called by an user. The former is not even documented.

I suggest to change this package in a way that these commands are hidden to users by default.

**Comment by jasonm23** [comment]
Since there are quite literally thousands of functions available to the user, which _should_ be hidden, add this one to the list.

Consider this as a won't fix.
