### ISSUE TITLE
Provide colors to end-user

### ISSUE THREAD

**Issue by mekeor** [greduan/emacs-theme-gruvbox#198]
### Feature request

How to access the colors defined in this package? E.g. when I have some personal face-customizations, I'd like to use the gruvbox-colors by their name.

```elisp
(use-package example
  :custom-face (org-done ((t (:foreground gruvbox-bright_red)))))
```

But the `gruvbox-bright_red` is not exposed by the package, if I understand correctly. Would love to see that be the case.

**Comment by jasonm23** [comment]
See autothemer the latest version will allow you to view palette, insert colers, missing faces etc
