### ISSUE TITLE
Bad contrast

### ISSUE THREAD

**Issue by Ikuyu** [greduan/emacs-theme-gruvbox#200]
### I'm submitting a:

Bug report

### Bug Report : Describe the problem in your own words

Bad contrast regarding the isearch/lazy-highlight/isearch-fail variables when using the 'light' variants (have a look at the supplied screenshots). I've attached some screenshots with the default settings (bad contrast) and the fixed stettings (good contrast) using a custom face.

### Please provide a relevant screenshot to illustrate the problem.

<img width="811" alt="Screenshot 2023-03-15 at 10 11 23" src="https://user-images.githubusercontent.com/57272868/225263444-562b7374-bafc-4348-9884-1e8ea4083a64.png">
<img width="97" alt="Screenshot 2023-03-15 at 10 11 38" src="https://user-images.githubusercontent.com/57272868/225263451-9c19a692-e163-4274-915a-ce3b330b2e68.png">
<img width="817" alt="Screenshot 2023-03-15 at 10 12 46" src="https://user-images.githubusercontent.com/57272868/225263452-67916547-1684-43e0-bbb1-1fbeccee8045.png">
<img width="101" alt="Screenshot 2023-03-15 at 10 13 50" src="https://user-images.githubusercontent.com/57272868/225263462-47aa9cf5-8a4c-4ead-9f5b-ec26d2720748.png">

### Please tell us about your environment.

- OS version:
  
  Latest version of macOS (Ventura)

- Emacs version:

  GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.6.0, Carbon Version 165 AppKit 2113.6) of 2022-09-15

- If your report is about a specific Emacs major or minor mode, please
  let us know how it was installed (MELPA, ELPA, by hand, etc.) and
  the major/minor-mode version number.

**Comment by ethanmoss1** [comment]
Ive submitted a pull request to fix this issue.

**Comment by Ikuyu** [comment]
Thank you.

I just happened to notice today that the same thing happens when using the package [avy](https://github.com/abo-abo/avy) with the dark variants of Gruvbox. The light variants do fine here, by the way.

**Comment by jasonm23** [comment]
Fixed by [6081c4c](https://github.com/greduan/emacs-theme-gruvbox/commit/6081c4cd7ef2dd5e01b9e59747b49aa2395b32d9)
