### ISSUE TITLE
Flag to use bold constructs

### ISSUE THREAD

**Issue by Ikuyu** [greduan/emacs-theme-gruvbox#201]
### I'm submitting a:

Feature request

### Feature request (ignore if this is a bug report.)

Is it possible to add a flag to use bold constructs as in the modus-themes (have a look at the screenshot)?

### Please provide a relevant screenshot to illustrate the problem.

<img width="811" alt="Screenshot 2023-03-15 at 10 25 37" src="https://user-images.githubusercontent.com/57272868/225266611-c8b2cd01-3c19-4233-96ac-592d49096e45.png">

### Please tell us about your environment.

- OS version:

  macOS Ventura

- Emacs version:

   GNU Emacs 28.2 (build 1, aarch64-apple-darwin21.6.0, Carbon Version 165 AppKit 2113.6) of 2022-09-15

- If your report is about a specific Emacs major or minor mode, please
  let us know how it was installed (MELPA, ELPA, by hand, etc.) and
  the major/minor-mode version number.

**Comment by ethanmoss1** [comment]
show-paren-mode already is bold within the theme. Might be the colours used that makes it less noticeable.

**Comment by jasonm23** [comment]
This will be closed in June if no PR's are submitted for it.

**Comment by ethanmoss1** [comment]
Feature request is regarding having Bold parentheses for the face attributed with show-paren-mode. This face is already Bold so I don't believe there's anything to be changed unless @Ikuyu has any suggestions?

**Comment by Ikuyu** [comment]
As you can see in the screenshot of the original question, the feature request is about printing certain keywords in bold.

**Comment by ethanmoss1** [comment]
Well call me a muppet, I should learn to read better!

I've got some time today I'll see if I can whip something up.

**Comment by ethanmoss1** [comment]
Played around with using defcustom and a group for gruvbox but decided to KISS.
(setq gruvbox-bold-constructs t) then load the theme and style of choice.

As an added extra I was in the process of adding Elpaca support so that in the pull request :)
