### ISSUE TITLE
Possible typo for bright-red and neutral-red in dark theme

### ISSUE THREAD

**Issue by zmberber** [greduan/emacs-theme-gruvbox#208]
### I'm submitting a:

- [x] Bug report

### Bug Report : Describe the problem in your own words

- In `gruvbox-dark-hard` we have
  - `(gruvbox-bright_red      "#fb4933" "#d75f5f")`
  - `(gruvbox-neutral_red     "#fb4934" "#d75f5f")`
- In `gruvbox-dark-medium` we have
  - `(gruvbox-bright_red      "#fb4933" "#d75f5f")`
  - `(gruvbox-neutral_red      "#fb4933" "#d75f5f")`
- In `gruvbox-dark-soft` we have
  - `(gruvbox-bright_red      "#fb4933" "#d75f5f")`
  - `(gruvbox-neutral_red     "#fb4933" "#d75f5f")`

This seems both inconsistent within itself, as well as inconsistent with the original [gruvbox "specification" of morhetz](https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim), which has these colors as `#fb4934`.

I know it is just a single unit off, but it still seems wrong this way.

So whatever is configured here seems like a typo.  Or is this on purpose and has some reason?

**Comment by jasonm23** [comment]
The Emacs Gruvbox historically took some liberties with the palette.

At this point the palette is now set and finalized.

**Comment by zmberber** [comment]
good to know, thanks!

it might be nice to have that mentioned in the readme, but oh well, it doesn't matter too much.  i'll close this issue.

out of curiosity, why were these specific choices made here?  i would imagine bigger differences if there were some liberties taken with the palette, like for stylistic reasons.   this here really just looks like a typo.  and it is inconsistent within itself, at least so it seems (what is regarded as "consistent" here is arbitrary, i guess, but still).

**Comment by jasonm23** [comment]
Greduan and myself (and all other contributors) simply look after the integration of new mode support. We're not the original author(s), and  have cared for Emacs Gruvbox a few years after it was originally put together.

Because Emacs and Vim cannot have 1:1 theme equivalency, Lee Machin (the original author)  didn't stick 100% to the Vim version of the theme either.

**Comment by zmberber** [comment]
i believe i understand what you are saying, and i can agree that stuff like this can be necessary or is just chosen like that for the aforementioned reasons.

still, whoever made this choice for the color here, i do not understand why this was done this way here, in this very specific instance.

so i guess i would have to direct my question towards whoever made this choice.  but whatever.  it's okay.  i can always change it myself i guess.
