### ISSUE TITLE
vim theme looks better

### ISSUE THREAD

**Issue by norbertklar** [greduan/emacs-theme-gruvbox#21]
Hello guys! This was my favourite theme in vim, but I don't know why did you changed the colors. Look at the picture:
![nb1qmi8](https://cloud.githubusercontent.com/assets/9632419/8286575/a538906e-190a-11e5-8781-8887815751e1.png)

Vim version on the left. Look at the difference! It so much better! Please remake your version, I'd like to use it. Thanks

**Comment by greduan** [comment]
I imagine it's because of how different the syntax highlighting engines are, and what they consider keywords and stuff differ. Not sure if fixable, but @jasonm23 can try. ;P

**Comment by norbertklar** [comment]
Will you message him? I'd really appreciate it.:)

**Comment by opsmanager-team** [comment]
@greduan is correct it's due to the differences in the syntax engines.

**Comment by norbertklar** [comment]
I hope, it'll be possible to remake this theme for good.

**Comment by jasonm23** [comment]
@norbertklar many people are already using this theme, and love it as it is.

While better is highly subjective, I don't necessarily disagree with you, it's simply that this theme on Emacs now has its own life.

**Comment by norbertklar** [comment]
And maybe can you remake as a new theme?

**Comment by greduan** [comment]
@norbertklar It'd be impossible to get exactly the same because of the highlighting engines. :/
Doesn't stop anyone from trying though.
