### ISSUE TITLE
Support vc-*-state faces

### ISSUE THREAD

**Issue by uqix** [greduan/emacs-theme-gruvbox#210]
### I'm submitting a:

- [x] Feature request

### Feature request

<img width="639" alt="image" src="https://github.com/greduan/emacs-theme-gruvbox/assets/10142314/ca74622e-f5ca-48c3-b247-7e93c7bcd925">

Currently they are all inherit `vc-state-base` without being themed, which is not usable.

**Comment by jasonm23** [comment]
Do please note that Emacs Gruvbox is user supported.

Feature requests are assumed to be pending pull requests from the submitter.

Thank you for your attention

**Comment by uqix** [comment]
As discussed in https://github.com/greduan/emacs-theme-gruvbox/pull/211#issuecomment-1954126764 , we can configure in init file like this:

```emacs-lisp

;; Used by dirvish
(set-face-attribute 'vc-edited-state nil :inherit 'diff-hl-change)
(set-face-attribute 'vc-locally-added-state nil :inherit 'diff-hl-insert)
(set-face-attribute 'vc-removed-state nil :inherit 'diff-hl-delete)

```
