### ISSUE TITLE
Export of highlighted, themed code possible?

### ISSUE THREAD

**Issue by j12i** [greduan/emacs-theme-gruvbox#212]
I hope it's okay to ask this here. I don't know where else to ask.

I want to present code on a website as close as possible to how I see it in Emacs when editing. There's a gruvbox theme for Pygments, but that takes different decisions on how to use colours.

left Emacs, right Pygments
![Screenshot_20240322_151054-1](https://github.com/greduan/emacs-theme-gruvbox/assets/2151851/0208e7de-0178-4253-b0a7-8cdb223e470e)

Is there a way to achieve this? 

If there's no good emacsoid way, I'm willing to get into the nitty-gritty of gruvbox-pygments CSS, but in order to do that I need to understand how emacs-theme-gruvbox decides to assign colours to syntax elements, and I already looked at the code but I'm at a loss there.

Thanks for reading this far! –Jay

- OS version:
    Slackware64 15.0
- Emacs version:
    GNU Emacs 27.2 (build 1, x86_64-slackware-linux-gnu, GTK+ Version 3.24.31) of 2022-12-08

**Comment by jasonm23** [comment]
Glad to help 👍🏽
