### ISSUE TITLE
Add spaceline support

### ISSUE THREAD

**Issue by onemanstartup** [greduan/emacs-theme-gruvbox#24]
new in emacs, using https://github.com/syl20bnr/spacemacs 
Text with powerline is dark on dark and not readable.

**Comment by jasonm23** [comment]
Screenshots pls.

**Comment by onemanstartup** [comment]
![image](https://cloud.githubusercontent.com/assets/980000/9195651/248391fe-402d-11e5-9a70-5d028d720918.png)
