### ISSUE TITLE
Keep README up-to-date

### ISSUE THREAD

**Issue by greduan** [greduan/emacs-theme-gruvbox#29]
@jasonm23 The README has "Supports" and "To-do" sections, while I kept these updated when I was maintaining the theme, I can't anymore.

You think you could keep these updated or perhaps remove them altogether from the README? What do you think is better?

Also the theme version, I kept that up-to-date more or less, but it doesn't seem to be maintained anymore. Perhaps pick a fixed (as in stuck) version number and use that?

I appreciate your maintainer status. :)

**Comment by jasonm23** [comment]
Ok I'll take care of those

**Comment by greduan** [comment]
@jasonm23 Thanks! :)
