### ISSUE TITLE
Auto-complete support

### ISSUE THREAD

**Issue by sleepmore** [greduan/emacs-theme-gruvbox#30]
![screenshot from 2015-12-26 17-48-11](https://cloud.githubusercontent.com/assets/8596459/12008250/ba83704e-abfc-11e5-9236-c41cd86ef7b5.png)

Auto-complete is a pretty cool package and it'd be nice to have some basic support for it with this theme. Just at least for the drop down pictured above, everything else works decently as is, the drop down is all that really stands out as wrong.

**Comment by jasonm23** [comment]
I'm only on phone for a few days. However there is support for Autocomplete in emacsfodder/Emacs-theme-Darktooth which is _almost_ a drop in.

You could have a look and play with it, or bump this thread in a week or so, then I can get it done.

**Comment by sleepmore** [comment]
![screenshot from 2015-12-27 00-19-06](https://cloud.githubusercontent.com/assets/8596459/12008943/8f4bc998-ac2f-11e5-98e6-f0f4c678b876.png)
Okay! Used your code from Darktooth and tweaked the colors, I I think it turned out pretty well. I'll submit a pull request now

**Comment by jasonm23** [comment]
Nice, that's completely on point for this theme/palette.

You may bump the version number too in your PR.

I will merge today after a quick review.

**Comment by jasonm23** [comment]
#31 fixes this :+1: thanks

**Comment by jasonm23** [comment]
Thank you @sleepmore Thomas
