### ISSUE TITLE
Merge / override with the newly developed gruvbox-dark.

### ISSUE THREAD

**Issue by jasonm23** [greduan/emacs-theme-gruvbox#32]

**Comment by jasonm23** [comment]
@d125q @greduan opening this up for discussion.

**Comment by greduan** [comment]
I'm not very into Emacs ATM, but I use gruvbox with vim so I can provide feedback. Of course I've admin to this repo so I can also add @d125q as a contributor if that'll make things easier.

From what I understand @d125q's repo has the same palette, but used differently so that it's less bright, is this correct? When I originally made the theme I made it so they used the same colors but I think gruvbox has had tons of changes since then so that may be a reason why they're not aligned.

**Comment by greduan** [comment]
@d125q any update on this? I'd like for this merge to happen but I would like your support, especially in understanding the differences. :)

**Comment by greduan** [comment]
For reference, here's a Reddit post's thread where this is discussed briefly (where this GitHub issue came from): https://www.reddit.com/r/emacs/comments/44oby0/gruvbox_dark_ported_to_gnu_emacs_with_better/czrp0pf

**Comment by jasonm23** [comment]
@d125q ping!

We would like to discuss merging our themes so that there's only one gruvbox.

Don't be concerned if you think you will lose control, we don't want that.

**Comment by d125q** [comment]
I am in the process of doing major improvements to my theme.  I will discuss this once I'm done.

**Comment by jasonm23** [comment]
@d125q bumping this, merge and collaboration.

**Comment by terinjokes** [comment]
@d125q Also bumping this. Would like to see the two themes merged together so there's one place to work on plugin/feature support.

This repo is the one linked to from the gruvbox contrib project, so where most people migrating over to emacs would end up.

**Comment by jasonm23** [comment]
thanks for the feedback @terinjokes - we are attempting to get this integration done soon.

I may use Darktooth as the core project and then create a palette plugin system so we may all share the mode theming.

Creamsody was built in about an hour as an offshoot of Darktooth.

There will be some mode themes which are impacted by this strategy so I will be figuring out a nice release strategy, (probably MELPA for edge and & MELPA Stable for the legacy so that people can get a feel for it.

**Comment by mekeor** [comment]
Is progress going on in this matter? If not, I could merge the two projects.

What about the license? emacs-theme-gruvbox is under MIT license and gruvbox-dark-emacs is under GPLv3. So, what'd be the license of the resulting code?

**Comment by jasonm23** [comment]
@d125q any updates on your end?

We are planning to fold in the palette, and any additional mode support you've added.

It will probably involve us rewriting to use Autothemer.

**Comment by jasonm23** [comment]
@mekeor did you look at / try out Autothemer yet?

**Comment by mekeor** [comment]
I just took a brief look. It's exactly what I was thinking about.

I'd like to merge gruvbox-dark-emacs and emacs-theme-gruvbox into a one theme. But still, I wonder what'd be the license of the result? I think it has to be GPL because gruvbox-dark-emacs is under GPL which has copyleft.

So, if we merge gruvbox-dark-emacs into emacs-theme-gruvbox, I think the most easiest way would be to change the license of emacs-theme-gruvbox into GPLv3. What do you think about this suggestion?

I could do the merge in the upcoming days. Maybe mostly tomorrow. I could create a new branch in an own fork.

**Comment by greduan** [comment]
Original author of this repo needs to be contacted if we want to change license to GPLv3, and he previously said no to changing license if I remember correctly.

I suggest simply dual licensing, this is possible between MIT and GPLv3, from what I understand.

**Comment by jasonm23** [comment]
@greduan - IMO it's simple and low impact to move gruvbox to GPL.

Plus we have control of this repo, and @d125q is (afaik) happy to integrate, just short on opportunity to communicate and act on the integration.

@mekeor I agree completely.  Autothemer is a project that was talked about over on the Darktooth theme project/repo but has not been used yet.

I'm a week away from my end of year vacation, I'm expecting to have some free time to code then.

**Comment by d125q** [comment]
I can re-license [gruvbox-dark-emacs](https://github.com/d125q/gruvbox-dark-emacs) if needed in order to make things compatible.

**Comment by jasonm23** [comment]
I have a feeling you can't revoke a GPL like licence.

We can simply re implement the code, because we'll be migrating to Autothemer when it's on MELPA

**Comment by jasonm23** [comment]
@greduan - If you have no objections I'll re-licence Gruvbox as GPL3

**Comment by greduan** [comment]
@jasonm23 Personally I don't like GPL3 (I prefer GPL2), but it's fine by me to relicense. Problem is original dev may not be if I remember correctly, and technically he's still a licensee.

However if it's fully new code, technically I've no right to name which license is used so go ahead and use what you want for new code. ;)

**Comment by jasonm23** [comment]
Noted.  I'll go ahead and change the license.

We can deal with problems if they arise.

**Comment by terinjokes** [comment]
@jasonm23 You can't change the license of previously released bits that were released under a GPL. But you can have the contributors agree to relicense their contributions under another license (in effect, dual-licensing their code). But, also, I'm not a lawyer.

**Comment by jasonm23** [comment]
It was released under MIT.  So there's nothing to be concerned about.

**Comment by greduan** [comment]
It will have to be dual-licensed. MIT is copyleft.

**Comment by jasonm23** [comment]
Afaik MIT is permissive, not copyleft.  @greduan can you point me at the specific section of the license you're referring to?

**Comment by jasonm23** [comment]
We will need to keep the MIT Licence notice in place but that's just to satisfy the MIT license itself.

Under other circumstances GPL3 will be the effective licence.

**Comment by greduan** [comment]
@jasonm23 

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

That's effectively copyleft, yes?

**Comment by jasonm23** [comment]
For the sake of argument, it's effectively copyleft.

The license is permissive and all factors of copyleft don't apply, but I don't think we need to concern ourselves with the complexity.

GPL3 will render any part of MIT which allows for permissive use, void.

GPL3 will also be an irrevocable license, that's the main issue I think we're facing.

We don't have any issues that I think are tangible though.  The theme is intended to be free and copyleft, so GPL3 makes sense

**Comment by greduan** [comment]
> GPL3 will also be an irrevocable license, that's the main issue I think we're facing.

So from what I can tell, we can actually change it.

Problem is if we want to change the license we need approval from each and every contributor of a "substantial amount of code" or whatever term the GPL uses to describe that, because they are also GPL copyright holders.

Baiscally, we can change the license, we just need permission from everybody since they automatically become copyright holders.

AFAIK IANAL.

**Comment by terinjokes** [comment]
@greduan which is why, if you want to keep it as MIT or similarly licensed code, now might be a good time. There's only 4 contributors to the other project.

**Comment by greduan** [comment]
@terinjokes It's no longer only my project. :slightly_smiling_face: While I prefer ISC/MIT, if it's for the better of the project I don't have a problem relicensing it under GPL.

**Comment by jasonm23** [comment]
@d125q I had a thought.  Since all we will effectively be doing is integrating your palette, we can probably just stay with the MIT License.

There's no way we could move forward (and cover a significant amount of package defined faxes) without keeping a uniform mapping of color palette vars to face specs.

Obviously you will be credited with the palette but I don't think GPL would apply to that specifically, it's quite difficult to copyright a color set.  Copyright would be protected on an execution of colors and shapes, so here it's under your copyright, however GPL is more concerned with source code.  So it will be up to you to decide if you are happy.

I think it would be a good idea to make sure anyone who contributed specifically to the color palette, also gave their consent.

**Comment by jasonm23** [comment]
`s/defined faxes/defined faces/`

**Comment by jasonm23** [comment]
@d125q  - please consider contributing any new patches to this repo. We have added light (soft, med, hard) and dark (soft + hard)

There is a single point where mode faces can be specified.

I think this takes care of the problems.
