### ISSUE TITLE
Change licence to GPL3 for merging with Gruvbox light (RFC)

### ISSUE THREAD

**Issue by jasonm23** [greduan/emacs-theme-gruvbox#58]
We are preparing to merge with Gruvbox light and wish to smooth the transfer by applying a compatible license.

GNU/GPL3

This issue is to reach out to contributors for comment.

Specifically @leemachin (as the original author of Emacs Gruvbox.) but anyone else who has contributed.

I will time box this RFC to 14 days and will change the license in Jan 2017 unless there is sufficient rationale to halt the relicense process.

**Comment by leemachin** [comment]
No complaint from me @jasonm23  :) I'm happy for you to do what you think is best.

**Comment by jasonm23** [comment]
Thanks @leemachin much appreciated..

The MIT License notice will remain (to satisfy the requirements of that license.) But once we publish the code under GPL3, it will supersede the MIT license.

Technically it will be dual license, but effectively GPL3 will override the MIT license.

(For clarification @greduan)

**Comment by mekeor** [comment]
If all copyright holders agree, you can change the license to whatever you want…

**Comment by jasonm23** [comment]
I'm reaching out to all contributors to Emacs Gruvbox

We would like to merge Emacs gruvbox themes, and we need to
reconsider licencing.

You're mentioned here if you've contributed more than a few lines of code:
@atheriel @zzgraph @Dominionized @rcoedo @torgeir @yasuyk @rdrr

Please respond to this thread and add you consent to allow us to
modify the license as we need, to accomplish the goal of
integrating with Gruvbox dark and Gruvbox light.

Many thanks.

Jasonm23
- Emacs Gruvbox maintainer.

**Comment by rcoedo** [comment]
I agree with whatever you think is good for the project 👍

**Comment by torgeir** [comment]
Seconded, go for it!

**Comment by Dominionized** [comment]
Thumbs up for me :+1:

**Comment by atheriel** [comment]
I'll happily relicense my contributions under the GPLv3. Good luck with the merge!

**Comment by greduan** [comment]
@jasonm23 I can do this, it's easy changes.

Should the copyright statements stay as-is (with GPL changes ofc) or should the copyright start anew for GPL?

In other words, should it be:

```
Copyright (c) 2013 Lee Machin
Copyright (c) 2013-2016 Greduan
Copyright (c) 2016-2017 Jason Milkins
```

Or:

```
Copyright (c) 2017 Jason Milkins
```

For the new GPL

**Comment by jasonm23** [comment]
BTW it seems we don't need to worry about using GPL now that we've merged Martijnat's light version implementation.  I don't think there's any legitimate need for the other Gruvbox package on MELPA now.
