### ISSUE TITLE
Some colors look off after updating.

### ISSUE THREAD

**Issue by TyphoidTony** [greduan/emacs-theme-gruvbox#59]
I just updated gruvbox today and there are a few colors that are darker than they used to be before updating it, namely the dark-red is sort of unreadable now.

**Comment by jasonm23** [comment]
Thanks for the heads up @TyphoidTony - we have integrated some palette changes, and I'm very interested in the feedback.

Can you provide a screengrab in this thread so I can get an idea of your user experience.

**Comment by jasonm23** [comment]
AFAICS dark-red has remained unchanged since it was added to the palette.  Would really like a screen grab, if you can find the older version in this repo and install it (package-install-file after removing gruvbox from your ELPA install.) that would really help nail the issue.

Thank you.

**Comment by mekeor** [comment]
I made the same experience. After updating today, many colors are broken. In this screenshot, red and blue are just wrong.

![grafik](https://cloud.githubusercontent.com/assets/812632/21524418/2df97204-cd16-11e6-8099-e5e441dfa2f5.png)

**Comment by jasonm23** [comment]
@mekeor please check the gruvbox dark PR that was integrated.

The colors are updated, not _wrong_

**Comment by jasonm23** [comment]
#56

**Comment by gilbertw1** [comment]
Could you please consider reverting the color update? After updating the package today I was instantly struck by how bad the theme looks. The readability has been drastically reduced, as you can see in the following before / after screenshots:

Before:
![Before](http://drop.bryangilbert.com/Lwux.png)

After:
![After](http://drop.bryangilbert.com/hPdk.png)

I took these screenshots before and after the following commit: 771243dc9200ceab054de32a987aa3aa6315c6ae

Thanks!

**Comment by jasonm23** [comment]
I am definitely considering a rollback.

I will say that I am using a different theme (except when developing Gruvbox) and so I'm not dogfooding.

Even so, I can certainly understand that changes can be jarring.

The color palette was modified to bring it into line with the Vim theme.  However, notably there are some differences in syntax highlighting too, so I don't think this update was such a fantastic move in retrospect.

I think the best thing we can do is rollback the palette and then include the other variants we have planned as alt themes in the same package.

**Comment by gilbertw1** [comment]
Thanks for the quick response! 

In order to sync the color palette with the vim theme, I'm thinking you'd probably have to significantly modify the theme to make it look good. I appreciate your work on this, I recently ported a different vim theme to emacs so I understand how difficult it can be to reproduce the feel of the original and keep it balanced.

**Comment by jasonm23** [comment]
@gilbertw1 yeah, generally avoid making promises about a 1:1 port of a Vim to Emacs theme.

The first piece of work is to create the light version.  I'm going to attempt that today.
