### ISSUE TITLE
Love the fonts!

### ISSUE THREAD

**Issue by lobachevzky** [greduan/emacs-theme-gruvbox#64]
Hi, 
I love the fonts you are using for your headers and examples. What's it called?

**Comment by greduan** [comment]
This only @jasonm23 can answer.

**Comment by jasonm23** [comment]
Hi it's SauceCodePro Nerd Font

**Comment by ninrod** [comment]
@lobachevzky, you should take a look at [office code pro](https://github.com/nathco/Office-Code-Pro). It's like source code pro, but with improvements.

**Comment by jasonm23** [comment]
All please note that SauceCodePro is not Source Code Pro.

**Comment by jasonm23** [comment]
https://github.com/ryanoasis/nerd-fonts
