### ISSUE TITLE
Magit support in light versions of the theme needs fixing

### ISSUE THREAD

**Issue by jasonm23** [greduan/emacs-theme-gruvbox#67]
As seen below Magit support needs tuning up 

![image](https://user-images.githubusercontent.com/71587/27516209-fcbf5064-59e7-11e7-9f0c-efece4eb2112.png)

![image](https://user-images.githubusercontent.com/71587/27516212-0e61d738-59e8-11e7-8b35-0af0262cf69a.png)

![image](https://user-images.githubusercontent.com/71587/27516214-183a5a5a-59e8-11e7-8c1d-13aa6936e145.png)

**Comment by martijnat** [comment]
I cannot reproduce the issue
![gruv1](https://user-images.githubusercontent.com/22380358/27517453-639d4900-59cd-11e7-92da-988be7af202a.png)
![gruv2](https://user-images.githubusercontent.com/22380358/27517454-639ee1ca-59cd-11e7-8f0a-cd9a58380ec6.png)
![gruv3](https://user-images.githubusercontent.com/22380358/27517455-63a2a7a6-59cd-11e7-8062-9c971a9bcb86.png)

Are you sure you are not overriding the faces from your personal config with custom-set-faces?

**Comment by jasonm23** [comment]
It's possible that the faces are set by another theme that wasn't properly
unloaded.

I will re-check shortly.

**Comment by jasonm23** [comment]
LGTM
