### ISSUE TITLE
ivy-current-match face is white with the light themes

### ISSUE THREAD

**Issue by spegoraro** [greduan/emacs-theme-gruvbox#68]
Loving the new theme variants! Nice work!

However ivy-current-match's face is just #ffffff at the moment which makes it hard to see with the light themes.

**Comment by jasonm23** [comment]
Thanks for using the new theme variants.  

We need people to report these problems, so thank you for the help.

I'll check the theme and get a fix in there asap.

**Comment by jasonm23** [comment]
@martijnat thank you

**Comment by jdahm** [comment]
I think something unintended happened with the #69 merge. It looks like the commit d6d54c6 only duplicates a section of pairs above the mu4e definitions. Could you double check that @martijnat?

**Comment by martijnat** [comment]
[It seems ivy support was already implemented earlier](https://github.com/greduan/emacs-theme-gruvbox/issues/52)

I was not aware of this and my addition was an unnecessary one it seems. It seems I have arrived at the same definitions by trying to find something close to the default faces.

The odd thing is that ivy-current-match did appear as #ffffff when using the light version and adding these faces fixed that.

**Comment by jdahm** [comment]
Great! I'll get around to using the latest version and test it later.

**Comment by jasonm23** [comment]
@martijnat I think we can probably replace all uses of gruvbox-white and black with their respective 0 hard counterparts.

**Comment by martijnat** [comment]
@jasonm23 I agree.

Perhaps it is also a good idea to rename grubox-dark to gruvbox-bg and rename gruvbox-light to gruvbox-fg.

**Comment by jdahm** [comment]
#72 Didn't quite fix it for me. The current match is underlined and shown in all white, no matter what substring is matched by the input.

**Comment by martijnat** [comment]
@jdahm I just tested it and It shows up with a black face and black underline using the light theme for me.

![ivy](https://user-images.githubusercontent.com/22380358/27748043-1e50b6f2-5dce-11e7-89d9-d6775618a195.png)

Could you confirm that

- You are using the latest version of gruvbox from melpa or git
- You have no customizations for ivy-current-match

**Comment by jdahm** [comment]
Oh okay, I misunderstood what you're trying to do. That's exactly what I see and no I don't have any of the customizations set. I thought you meant that you wanted the match to show even on the currently-selected item as well as the others.

By the way, how do you get ivy to give you a list of the customization headings like that?

**Comment by martijnat** [comment]
I think this is normal ivy behaviour. I normally use ido for completions so I could be wrong without knowing it.

> By the way, how do you get ivy to give you a list of the customization headings like that?

    M-x customize-group ivy-faces

**Comment by jasonm23** [comment]
@martijnat @jdahm almost completely off topic, but compared to ido vertical + fuzzy matching (assuming you've tried it) what differences do you have using ivy?

**Comment by martijnat** [comment]
@jasonm23 many small nuances, most of them are better/worse based on your preferences. I actually prefer *not* to have fuzzy matching since for me it is more error prone and use ido-horizontal because I do not want my minibuffer to change size.

**Comment by zzgraph** [comment]
@jasonm23 one reason to use ivy-counsel-swiper may be a consistency anywhere from `M-x` to `C-h *` to `C-s` and also `C-x C-b` and `C-x C-f`
