### ISSUE TITLE
Move images into their own folder

### ISSUE THREAD

**Issue by greduan** [greduan/emacs-theme-gruvbox#70]
Would be nice to move all the images to their own folder so they don't clutter the repo source code, also would allow (if this is a feature) to have something similar to an `.npmignore`, where distribution channels have a folder (`images/`) that they don't want to include in order to save bandwidth.

**Comment by jasonm23** [comment]
I'll take care of this today

**Comment by jasonm23** [comment]
(today, for reals this time (was in Thailand without WiFi for the weekend))

**Comment by jasonm23** [comment]
#74
