### ISSUE TITLE
Company quickhelp tool tip and company templates

### ISSUE THREAD

**Issue by zzgraph** [greduan/emacs-theme-gruvbox#77]
I'm working on some faces of company like template and tool tip, I want to know if you think these changes are ok, or you have any suggestion about it
company-templates
![company-template Before](https://user-images.githubusercontent.com/1885156/27938299-902e3aa0-62ac-11e7-9d73-60dfcdded883.png)
![company-template After](https://user-images.githubusercontent.com/1885156/27938307-a5a1bf1a-62ac-11e7-9b6c-4d04a3cb3d8c.png)

Preview only selection
![company-preview before](https://user-images.githubusercontent.com/1885156/27938320-c1c1ff2a-62ac-11e7-99a1-edb653fb0c8f.png)
![company-preview After](https://user-images.githubusercontent.com/1885156/27938367-2ae90b9c-62ad-11e7-87b7-7589a709278b.png)

Tool Tip
This is company-quickhelp pos-tip after applying  theme
![screenshot from 2017-07-07 05-14-27](https://user-images.githubusercontent.com/1885156/27938450-ab04340a-62ad-11e7-96c4-ef5aa00d75cc.png)
this is Befor
![screenshot from 2017-07-06 19-20-04](https://user-images.githubusercontent.com/1885156/27938457-b677c2de-62ad-11e7-920b-95b8772072bf.png)

**Comment by jasonm23** [comment]
@zzgraph please post clean screenshots, these have some sort of color overlay.

**Comment by zzgraph** [comment]
I'm gonna send clearer screenshots in a respective pull request.

**Comment by martijnat** [comment]
Since #80 is now merged, this issue should be closed
