### ISSUE TITLE
add support for the new native line number feature, in emacs master

### ISSUE THREAD

**Issue by ninrod** [greduan/emacs-theme-gruvbox#83]
as demonstrated [here](http://i.imgur.com/XvmKcO9.png)

**Comment by jasonm23** [comment]
![](https://i.imgur.com/XvmKcO9_d.jpg?maxwidth=640&shape=thumb&fidelity=high)

Does this match the current linum definitions?

**Comment by jasonm23** [comment]
Looks like we need to align linum and relative linum too.  Everything can be done in one shot.

If it's still needs doing by tonight (Singapore time) I'll get this done.

**Comment by ninrod** [comment]
@jasonm23, here's what I did in my gruvbox [fork](https://github.com/ninrod/gruvbox-theme): [snippet](https://github.com/ninrod/gruvbox-theme/blob/322aa88dcb5ff82c36605e6cd28bff1edbaae6bd/gruvbox-theme.el#L341-L342)

**Comment by jasonm23** [comment]
Fixed by #84
