### ISSUE TITLE
Add @martijnat as contributor

### ISSUE THREAD

**Issue by greduan** [greduan/emacs-theme-gruvbox#86]
@jasonm23 

You think it'd be good to add @martijnat as a contributor? He has been making many PRs.

I propose this so that there's a more direct way for him to contribute of course, and to acknowledge his contributions.

Let me know. And I hope no pressure/hard feelings if the answer for you is no. 🙂

**Comment by jasonm23** [comment]
I think @martijnat has proved they're able to keep the faces / palette on track and I certainly appreciate all the effort going into the themes currently.

It's a great idea. 

I will only ask that patches are still put in as pull requests so that they're reviewed before merge.

**Comment by greduan** [comment]
You OK with being a contributor @martijnat ? 🙂

**Comment by martijnat** [comment]
> I will only ask that patches are still put in as pull requests so that they're reviewed before merge.

Fine with me.

So the main change would be that I can approve other peoples pull requests and close issues?

**Comment by martijnat** [comment]
> You OK with being a contributor @martijnat ? 🙂

Yes.

> I will only ask that patches are still put in as pull requests so that they're reviewed before merge.

Fine with me

**Comment by greduan** [comment]
> So the main change would be that I can approve other peoples pull requests and close issues?

In that case I believe so, yes.

**Comment by martijnat** [comment]
@greduan @jasonm23 
Perhaps there was some miscomunication. I have the status of "contributor", which I think is just a title for anybody whose pull request has been accepted. I don't seem to have any special priveledges such as closing issues. I suspect you meant "Collaborator", the status that jason has.

**Comment by greduan** [comment]
That was my intention yes. I didn't do it though.
