### ISSUE TITLE
Light variants of theme look bad in terminal

### ISSUE THREAD

**Issue by martijnat** [greduan/emacs-theme-gruvbox#87]
Background colors look like faded plastic and the mode line is gray

All screenshots are GUI first, terminal second with same dimensions and font. I got the same colors on xterm, gnome-terminal and xfce4-terminal.

I am not exactly sure what RGB colors are valid colors in 256 color mode so I am hesitant to pick something that works on my machine that might not work on other terminal emulators.

Light-hard is acceptable
![gui-gruvbox-light-hard](https://user-images.githubusercontent.com/22380358/28329192-3ca9ee24-6be9-11e7-86e5-17ba48727dd3.png)
![term-gruvbox-light-hard](https://user-images.githubusercontent.com/22380358/28329080-d1be9876-6be8-11e7-87c4-c224422c5a22.png)

Light-medium is yellow
![gui-gruvbox-light-medium](https://user-images.githubusercontent.com/22380358/28329228-5f5d60c2-6be9-11e7-9205-aa7b98fb5bd0.png)
![term-gruvbox-light-medium](https://user-images.githubusercontent.com/22380358/28329079-d1bb658e-6be8-11e7-88d6-54ef6764e4a1.png)

Light-soft is the same shade of yellow
![gui-gruvbox-light-soft](https://user-images.githubusercontent.com/22380358/28329235-6797f888-6be9-11e7-8ab4-31684ebabadb.png)
![term-gruvbox-light-soft](https://user-images.githubusercontent.com/22380358/28329081-d1cd916e-6be8-11e7-8fac-63409882c93e.png)

**Comment by ninrod** [comment]
@martijnat, what version of emacs are you using. seems that there's a merged patch in master that supports true color. Maybe it's not the case of messing with these colors in the 256-color version of the terminal as the emacs-26 release will contain the truecolor terminal support.

**Comment by martijnat** [comment]
> @martijnat, what version of emacs are you using?

I compiled from master 2 days ago. `M-x emacs-version` gives me

`GNU Emacs 26.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.16) of 2017-07-17`

However even if emacs supported truecolor in the terminal you would want it to still work with 256-color terminals.

**Comment by martijnat** [comment]
I have proposed an updated color scheme in https://github.com/greduan/emacs-theme-gruvbox/pull/88

**Comment by lmumar** [comment]
That's a nice font! what's that font?

**Comment by martijnat** [comment]
The font is called envypn
